#import <AppKit/AppKit.h>
#import "TalariaModels.h"

NS_ASSUME_NONNULL_BEGIN

#ifdef __cplusplus
extern "C" {
#endif

NSColor *TLColorFromHex(NSUInteger hexValue);
NSColor *TLColorWithAlpha(NSColor *color, CGFloat alpha);
NSColor *TLContentAccentColorWithAlpha(NSColor *color, CGFloat alpha);
NSColor *TLColorByInterpolatingColors(NSColor *startColor, NSColor *endColor, CGFloat progress);
CGColorRef TLCGColor(NSColor *color);

#ifdef __cplusplus
}
#endif

@interface TLThemePalette : NSObject

@property (nonatomic) BOOL dark;

@property (nonatomic, strong) NSColor *black;
@property (nonatomic, strong) NSColor *white;
@property (nonatomic, strong) NSColor *gray50;
@property (nonatomic, strong) NSColor *gray100;
@property (nonatomic, strong) NSColor *gray200;
@property (nonatomic, strong) NSColor *gray300;
@property (nonatomic, strong) NSColor *gray400;
@property (nonatomic, strong) NSColor *gray500;
@property (nonatomic, strong) NSColor *gray600;
@property (nonatomic, strong) NSColor *gray700;
@property (nonatomic, strong) NSColor *gray800;
@property (nonatomic, strong) NSColor *gray900;
@property (nonatomic, strong) NSColor *gray950;
@property (nonatomic, strong) NSColor *blue300;
@property (nonatomic, strong) NSColor *blue500;
@property (nonatomic, strong) NSColor *blue600;
@property (nonatomic, strong) NSColor *green500;
@property (nonatomic, strong) NSColor *red500;

@property (nonatomic, strong) NSColor *appText;
@property (nonatomic, strong) NSColor *appBackground;
@property (nonatomic, strong) NSColor *appContentBackground;
@property (nonatomic, strong) NSColor *tabBackground;
@property (nonatomic, strong) NSColor *transparentSurface;
@property (nonatomic, strong) NSColor *frostedOverlay;
@property (nonatomic, strong) NSColor *chromeHoverSurface;
@property (nonatomic, strong) NSColor *taskStatusPillSurface;
@property (nonatomic, strong) NSColor *taskStatusPillBorder;
@property (nonatomic, strong) NSColor *topbarBorder;
@property (nonatomic, strong) NSColor *brandMark;
@property (nonatomic, strong) NSColor *statusItemIcon;
@property (nonatomic, strong) NSColor *textMuted;
@property (nonatomic, strong) NSColor *labelText;
@property (nonatomic, strong) NSColor *controlSurface;
@property (nonatomic, strong) NSColor *controlText;
@property (nonatomic, strong) NSColor *controlBorder;
@property (nonatomic, strong) NSColor *controlFocus;
@property (nonatomic, strong) NSColor *sidebarSurface;
@property (nonatomic, strong) NSColor *sidebarBorder;
@property (nonatomic, strong) NSColor *sidebarActiveSurface;
@property (nonatomic, strong) NSColor *sidebarHoverSurface;
@property (nonatomic, strong) NSColor *sidebarInboxBadgeSurface;
@property (nonatomic, strong) NSColor *sidebarInboxBadgeText;
@property (nonatomic, strong) NSColor *sidebarInboxPrimaryBadgeSurface;
@property (nonatomic, strong) NSColor *sidebarInboxPrimaryBadgeText;
@property (nonatomic, strong) NSColor *sidebarUrgentNotificationPulseSurface;
@property (nonatomic, strong) NSColor *sidebarUrgentNotificationBadgeSurface;
@property (nonatomic, strong) NSColor *sidebarUrgentNotificationBadgeText;
@property (nonatomic, strong) NSColor *sidebarNotesShortcutIcon;
@property (nonatomic, strong) NSColor *sidebarHistoryShortcutIcon;
@property (nonatomic, strong) NSColor *tabBorder;
@property (nonatomic, strong) NSColor *tabActiveBorder;
@property (nonatomic, strong) NSColor *historyRowActiveSurface;
@property (nonatomic, strong) NSColor *modalBackdrop;
@property (nonatomic, strong) NSColor *messagesSurface;
@property (nonatomic, strong) NSColor *emptyText;
@property (nonatomic, strong) NSColor *chipBorder;
@property (nonatomic, strong) NSColor *chipText;
@property (nonatomic, strong) NSColor *chipSurface;
@property (nonatomic, strong) NSColor *userMessageSurface;
@property (nonatomic, strong) NSColor *userMessageText;
@property (nonatomic, strong) NSColor *assistantMessageSurface;
@property (nonatomic, strong) NSColor *assistantMessageText;
@property (nonatomic, strong) NSColor *assistantMessageBorder;
@property (nonatomic, strong) NSColor *messageShadow;
@property (nonatomic, strong) NSColor *contentShadow;
@property (nonatomic, strong) NSColor *glassButtonHoverTint;
@property (nonatomic, strong) NSColor *agentWalletTransactionsSurface;
@property (nonatomic, strong) NSColor *agentWalletTransactionPrimaryText;
@property (nonatomic, strong) NSColor *agentWalletBalanceCaptionText;
@property (nonatomic, strong) NSColor *agentWalletTransactionDateText;
@property (nonatomic, strong) NSColor *agentWalletTransactionDetailText;
@property (nonatomic, strong) NSColor *agentWalletIssuerText;
@property (nonatomic, strong) NSColor *agentWalletTopUpSurface;
@property (nonatomic, strong) NSColor *agentWalletTopUpHoverSurface;
@property (nonatomic, strong) NSColor *agentWalletTopUpText;
@property (nonatomic, strong) NSColor *thinkingBorder;
@property (nonatomic, strong) NSColor *thinkingText;
@property (nonatomic, strong) NSColor *markdownCodeSurface;
@property (nonatomic, strong) NSColor *markdownCodeText;
@property (nonatomic, strong) NSColor *markdownCodeBorder;
@property (nonatomic, strong) NSColor *markdownQuoteBorder;
@property (nonatomic, strong) NSColor *markdownQuoteText;
@property (nonatomic, strong) NSColor *markdownTableBorder;
@property (nonatomic, strong) NSColor *markdownTableHeaderSurface;
@property (nonatomic, strong) NSColor *markdownTableAlternateRowSurface;
@property (nonatomic, strong) NSColor *markdownLinkText;
@property (nonatomic, strong) NSColor *composerBorder;
@property (nonatomic, strong) NSColor *composerSurface;
@property (nonatomic, strong) NSColor *slashCommandItemSurface;
@property (nonatomic, strong) NSColor *slashCommandItemText;
@property (nonatomic, strong) NSColor *slashCommandItemHighlightedSurface;
@property (nonatomic, strong) NSColor *slashCommandItemHighlightedText;
@property (nonatomic, strong) NSColor *messageInputPlaceholderText;
@property (nonatomic, strong) NSColor *messageInputSendButtonSurface;
@property (nonatomic, strong) NSColor *messageInputSendButtonDisabledSurface;
@property (nonatomic, strong) NSColor *messageInputSendButtonText;
@property (nonatomic, strong) NSColor *primaryActionSurface;
@property (nonatomic, strong) NSColor *primaryActionText;
@property (nonatomic, strong) NSColor *secondaryActionSurface;
@property (nonatomic, strong) NSColor *secondaryActionText;
@property (nonatomic, strong) NSColor *notchOverlayWindowBackground;
@property (nonatomic, strong) NSColor *notchOverlaySurface;
@property (nonatomic, strong) NSColor *notchOverlayText;
@property (nonatomic, strong) NSColor *notchOverlayProgress;
@property (nonatomic, strong) NSColor *notchOverlayProgressTrack;
@property (nonatomic, strong) NSColor *notchOverlayDropTargetBorder;
@property (nonatomic, strong) NSColor *onboardingDemoBackgroundTop;
@property (nonatomic, strong) NSColor *onboardingDemoBackgroundBottom;
@property (nonatomic, strong) NSColor *onboardingDemoCaptionText;
@property (nonatomic, strong) NSColor *onboardingDemoAlternativeBrowserCorrectionText;
@property (nonatomic, strong) NSColor *onboardingDemoTitleStrike;
@property (nonatomic, strong) NSColor *onboardingDemoOpenAppButtonSurface;
@property (nonatomic, strong) NSColor *onboardingDemoOpenAppButtonText;
@property (nonatomic, strong) NSColor *onboardingDemoCubeFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoSafariFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoAutomatorFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoNotesFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoTalariaFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoTalariaFaceGradientTop;
@property (nonatomic, strong) NSColor *onboardingDemoTalariaFaceGradientBottom;
@property (nonatomic, strong) NSColor *onboardingDemoAlternativeBrowserFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoAlternativeBrowserFaceGradientTop;
@property (nonatomic, strong) NSColor *onboardingDemoAlternativeBrowserFaceGradientBottom;
@property (nonatomic, strong) NSColor *onboardingDemoCapFaceSurface;
@property (nonatomic, strong) NSColor *onboardingDemoCubeFaceBorder;

@property (nonatomic) CGFloat topbarHeight;
@property (nonatomic) CGFloat taskStatusPillHeight;
@property (nonatomic) CGFloat taskStatusIndicatorSize;
@property (nonatomic) CGFloat taskStatusIndicatorDotSize;
@property (nonatomic) CGFloat taskStatusIndicatorInactiveOpacity;
@property (nonatomic) CGFloat taskStatusIndicatorBlinkDuration;
@property (nonatomic) CGFloat agentWalletIntroPopoverWidth;
@property (nonatomic) CGFloat agentWalletDetailsPopoverWidth;
@property (nonatomic) CGFloat agentWalletCardWidth;
@property (nonatomic) CGFloat agentWalletCardHeight;
@property (nonatomic) CGFloat agentWalletDetailsCardWidth;
@property (nonatomic) CGFloat agentWalletDetailsCardHeight;
@property (nonatomic) CGFloat agentWalletCardShadowOpacity;
@property (nonatomic) CGFloat agentWalletCardShadowRadius;
@property (nonatomic) CGFloat agentWalletCardShadowOffsetY;
@property (nonatomic) CGFloat agentWalletOverviewContentGap;
@property (nonatomic) CGFloat agentWalletOverviewActionGap;
@property (nonatomic) CGFloat agentWalletOverviewActionRowGap;
@property (nonatomic) CGFloat agentWalletIntroButtonHeight;
@property (nonatomic) CGFloat agentWalletTopUpButtonHeight;
@property (nonatomic) CGFloat agentWalletSeeAllButtonWidth;
@property (nonatomic) CGFloat agentWalletSeeAllButtonHeight;
@property (nonatomic) CGFloat agentWalletTransactionIconSize;
@property (nonatomic) CGFloat agentWalletTransactionIconTextGap;
@property (nonatomic) CGFloat agentWalletTransactionSeparatorOpacity;
@property (nonatomic) CGFloat agentWalletIssuerGap;
@property (nonatomic) CGFloat windowInitialWidth;
@property (nonatomic) CGFloat windowInitialHeight;
@property (nonatomic) CGFloat windowMinimumWidth;
@property (nonatomic) CGFloat windowMinimumHeight;
@property (nonatomic) CGFloat trafficLightLeftInset;
@property (nonatomic) CGFloat trafficLightReservedWidth;
@property (nonatomic) CGFloat sidebarWidth;
@property (nonatomic) CGFloat sidebarMinimumWidth;
@property (nonatomic) CGFloat sidebarMaximumWidth;
@property (nonatomic) CGFloat sidebarTileSelectedBorderWidth;
@property (nonatomic) CGFloat sidebarTileSelectedAccentFillOpacity;
@property (nonatomic) CGFloat sidebarTileSystemIconSize;
@property (nonatomic) CGFloat sidebarAgentTileMaximumWidth;
@property (nonatomic) CGFloat sidebarAccessoryIconOpacity;
@property (nonatomic) CGFloat sidebarActionIconSize;
@property (nonatomic) CGFloat sidebarActionStackHorizontalInset;
@property (nonatomic) CGFloat sidebarContentLeadingInset;
@property (nonatomic) CGFloat sidebarContentTrailingInset;
@property (nonatomic) CGFloat sidebarActionStackLeadingInset;
@property (nonatomic) CGFloat sidebarActionStackTrailingInset;
@property (nonatomic) CGFloat sidebarActionItemHorizontalInset;
@property (nonatomic) CGFloat sidebarActionItemContentGap;
@property (nonatomic) CGFloat sidebarInboxOuterHorizontalInset;
@property (nonatomic) CGFloat sidebarInboxItemHorizontalInset;
@property (nonatomic) CGFloat sidebarInboxHeaderItemGap;
@property (nonatomic) CGFloat sidebarInboxItemLeadingOffset;
@property (nonatomic) CGFloat sidebarInboxIconSize;
@property (nonatomic) CGFloat sidebarInboxBadgeHorizontalPadding;
@property (nonatomic) CGFloat sidebarInboxBadgeMinimumWidth;
@property (nonatomic) CGFloat sidebarBookmarkButtonSize;
@property (nonatomic) CGFloat sidebarBookmarkIconSize;
@property (nonatomic) CGFloat sidebarBookmarkSpacing;
@property (nonatomic) CGFloat sidebarBookmarkCornerRadius;
@property (nonatomic) CGFloat tabHeight;
@property (nonatomic) CGFloat compactButtonSurfaceSize;
@property (nonatomic) CGFloat compactButtonSurfaceOffsetX;
@property (nonatomic) CGFloat compactButtonCornerRadius;
@property (nonatomic) CGFloat tabActiveHeightReduction;
@property (nonatomic) CGFloat tabMinWidth;
@property (nonatomic) CGFloat tabMaxWidth;
@property (nonatomic) CGFloat tabIconSize;
@property (nonatomic) CGFloat tabIconGlyphSize;
@property (nonatomic) CGFloat tabEmojiVerticalOffset;
@property (nonatomic) CGFloat tabIconLeadingInset;
@property (nonatomic) CGFloat tabIconTextSpacing;
@property (nonatomic) CGFloat menuActionIconTextSpacing;
@property (nonatomic) CGFloat menuActionIconUpwardOffset;
@property (nonatomic) CGFloat agentSharedIconDownwardOffset;
@property (nonatomic) CGFloat agentSharedLabelDownwardOffset;
@property (nonatomic) CGFloat agentMenuAvatarSize;
@property (nonatomic) CGFloat agentTileBadgeWidth;
@property (nonatomic) CGFloat agentTileBadgeHeight;
@property (nonatomic) CGFloat agentTileBadgeIconSize;
@property (nonatomic) CGFloat agentTileBadgeInset;
@property (nonatomic) CGFloat tabFlareRadius;
@property (nonatomic) CGFloat tabSelectionSlideDuration;
@property (nonatomic) CGFloat tabMetadataTransitionDuration;
@property (nonatomic) CGFloat tabSelectionLongJumpDistanceMultiplier;
@property (nonatomic) CGFloat tabReorderSlideDuration;
@property (nonatomic) CGFloat tabLifecycleTransitionDuration;
@property (nonatomic) CGFloat tabLifecycleCollapsedWidthRatio;
@property (nonatomic) CGFloat tabLifecycleContentFadeDurationRatio;
@property (nonatomic) CGFloat tabInsertionFadeStartProgress;
@property (nonatomic) CGFloat tabInsertionFadeEndProgress;
@property (nonatomic) CGFloat tabSeparatorFadeDuration;
@property (nonatomic) CGFloat tabHoverFadeDuration;
@property (nonatomic) CGFloat historyRowHeight;
@property (nonatomic) CGFloat historyRowSelectionHorizontalInset;
@property (nonatomic) CGFloat historyRowSelectionVerticalInset;
@property (nonatomic) CGFloat composerMinHeight;
@property (nonatomic) CGFloat composerButtonHeight;
@property (nonatomic) CGFloat messageInputSendButtonSize;
@property (nonatomic) CGFloat messageInputMaxHeight;
@property (nonatomic) CGFloat browserBackdropHeight;
@property (nonatomic) CGFloat browserToolbarButtonSize;
@property (nonatomic) CGFloat browserToolbarIconSize;
@property (nonatomic) CGFloat browserReducedHeightSpacing;
@property (nonatomic) CGFloat browserHeightTransitionDuration;
@property (nonatomic) CGFloat browserHeightTransitionOvershoot;
@property (nonatomic) CGFloat browserChatPaneHeightFraction;
@property (nonatomic) CGFloat browserChatPaneTransitionDuration;
@property (nonatomic) CGFloat browserChatPaneSlideDistance;
@property (nonatomic) CGFloat messageInputCornerRadius;
@property (nonatomic) CGFloat slashCommandListCornerRadius;
@property (nonatomic) CGFloat slashCommandRowHeight;
@property (nonatomic) CGFloat messageInputMinWidth;
@property (nonatomic) CGFloat messageInputMaxWidth;
@property (nonatomic) CGFloat messageMaxWidth;
@property (nonatomic) CGFloat messageHorizontalInset;
@property (nonatomic) CGFloat messageVerticalSpacing;
@property (nonatomic) CGFloat userMessageMaxWidthMultiplier;
@property (nonatomic) CGFloat assistantMessageMaxWidthMultiplier;
@property (nonatomic) CGFloat controlMinWidth;
@property (nonatomic) CGFloat fieldHeight;
@property (nonatomic) CGFloat settingsSheetWidth;
@property (nonatomic) CGFloat settingsSheetHeight;
@property (nonatomic) CGFloat settingsActionHeight;
@property (nonatomic) CGFloat brandMarkSize;
@property (nonatomic) CGFloat brandMarkInset;
@property (nonatomic) CGFloat brandMarkStrokeWidth;
@property (nonatomic) CGFloat brandMarkDotRadius;
@property (nonatomic) CGFloat brandMarkCrossInset;
@property (nonatomic) CGFloat focusRingSize;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat workspaceOutlineOpacity;
@property (nonatomic) CGFloat radiusMedium;
@property (nonatomic) CGFloat radiusPill;
@property (nonatomic) CGFloat chipRadius;
@property (nonatomic) CGFloat chipVerticalPadding;
@property (nonatomic) CGFloat onboardingDemoOpenAppButtonHeight;
@property (nonatomic) CGFloat onboardingDemoOpenAppButtonHorizontalPadding;
@property (nonatomic) CGFloat onboardingDemoOpenAppButtonTopOffset;
@property (nonatomic) CGFloat space0;
@property (nonatomic) CGFloat space2;
@property (nonatomic) CGFloat space3;
@property (nonatomic) CGFloat space4;
@property (nonatomic) CGFloat space5;
@property (nonatomic) CGFloat space6;
@property (nonatomic) CGFloat space8;
@property (nonatomic) CGFloat space9;
@property (nonatomic) CGFloat space10;
@property (nonatomic) CGFloat space11;
@property (nonatomic) CGFloat space12;
@property (nonatomic) CGFloat space16;
@property (nonatomic) CGFloat roleOpacity;
@property (nonatomic) CGFloat disabledOpacity;
@property (nonatomic) CGFloat notchOverlayMinimumWidth;
@property (nonatomic) CGFloat notchOverlayMinimumHeight;
@property (nonatomic) CGFloat notchOverlayFallbackNotchWidth;
@property (nonatomic) CGFloat notchOverlayHorizontalPadding;
@property (nonatomic) CGFloat notchOverlayVerticalPadding;
@property (nonatomic) CGFloat notchOverlayTopOffset;
@property (nonatomic) CGFloat notchOverlayTopFlareOutset;
@property (nonatomic) CGFloat notchOverlayTopFlareHeight;
@property (nonatomic) CGFloat notchOverlayProximity;
@property (nonatomic) CGFloat notchOverlayCornerRadius;
@property (nonatomic) CGFloat notchOverlayTrackingInterval;
@property (nonatomic) CGFloat notchOverlayAnimationExpandDuration;
@property (nonatomic) CGFloat notchOverlayAnimationSettleDuration;
@property (nonatomic) CGFloat notchOverlayAnimationHideDuration;
@property (nonatomic) CGFloat notchOverlayAnimationOvershootScale;
@property (nonatomic) CGFloat notchOverlayDropMinimumWidth;
@property (nonatomic) CGFloat notchOverlayDropMinimumHeight;
@property (nonatomic) CGFloat notchOverlayDropHorizontalPadding;
@property (nonatomic) CGFloat notchOverlayDropVerticalPadding;
@property (nonatomic) CGFloat notchOverlayDropPromptDuration;
@property (nonatomic) CGFloat notchOverlayProgressHeight;
@property (nonatomic) CGFloat notchOverlayDropTargetInset;
@property (nonatomic) CGFloat notchOverlayDropIconSize;
@property (nonatomic) CGFloat notchOverlayDropIconSlideDistance;
@property (nonatomic) CGFloat notchOverlayDropIconAnimationDuration;
@property (nonatomic) CGFloat notchOverlayDropGlareDuration;
@property (nonatomic) CGFloat notchOverlayDropGlareOpacity;

@property (nonatomic, strong) NSFont *bodyFont;
@property (nonatomic, strong) NSFont *messageBodyFont;
@property (nonatomic, strong) NSFont *smallFont;
@property (nonatomic, strong) NSFont *labelFont;
@property (nonatomic, strong) NSFont *sidebarActionTitleFont;
@property (nonatomic, strong) NSFont *sidebarInboxUnreadTitleFont;
@property (nonatomic, strong) NSFont *sidebarInboxReadTitleFont;
@property (nonatomic, strong) NSFont *sidebarInboxBadgeFont;
@property (nonatomic, strong) NSFont *tabIconFont;
@property (nonatomic, strong) NSFont *roleFont;
@property (nonatomic, strong) NSFont *titleFont;
@property (nonatomic, strong) NSFont *emptyTitleFont;
@property (nonatomic, strong) NSFont *notchOverlayLabelFont;
@property (nonatomic, strong) NSFont *onboardingDemoCaptionFont;
@property (nonatomic, strong) NSFont *onboardingDemoAlternativeBrowserCorrectionFont;
@property (nonatomic, strong) NSFont *onboardingDemoOpenAppButtonFont;
@property (nonatomic, strong) NSFont *agentWalletIntroTitleFont;
@property (nonatomic, strong) NSFont *agentWalletIntroSubtitleFont;
@property (nonatomic, strong) NSFont *agentWalletIntroButtonFont;
@property (nonatomic, strong) NSFont *agentWalletBalanceTitleFont;
@property (nonatomic, strong) NSFont *agentWalletBalanceCaptionFont;
@property (nonatomic, strong) NSFont *agentWalletBalanceAmountFont;
@property (nonatomic, strong) NSFont *agentWalletSectionTitleFont;
@property (nonatomic, strong) NSFont *agentWalletTransactionDateFont;
@property (nonatomic, strong) NSFont *agentWalletTransactionTitleFont;
@property (nonatomic, strong) NSFont *agentWalletTransactionDetailFont;
@property (nonatomic, strong) NSFont *agentWalletTransactionAmountFont;
@property (nonatomic, strong) NSFont *markdownHeading1Font;
@property (nonatomic, strong) NSFont *markdownHeading2Font;
@property (nonatomic, strong) NSFont *markdownHeading3Font;
@property (nonatomic, strong) NSFont *markdownCodeFont;

+ (instancetype)paletteForPreference:(TLThemePreference)preference;
+ (instancetype)paletteForPreference:(TLThemePreference)preference effectiveAppearance:(nullable NSAppearance *)appearance;
+ (BOOL)isDarkEffectiveAppearance;

@end

NS_ASSUME_NONNULL_END
